# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instapass-guard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instapass-guard

  target 'instapass-guardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire-SwiftyJSON'
  pod 'QRCodeReader.swift'

end
