# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'instapass-guard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instapass-guard

  target 'instapass-guardTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'EFQRCode', '~> 5.1.6'
  pod 'Alamofire-SwiftyJSON'
  pod 'QRCodeReader.swift'
  pod 'IQKeyboardManager'
  pod 'SPAlert'
  pod 'Pageboy', '~> 3.6'
end
